export const CALENDAR_ERROR = "CALENDAR_ERROR";
export const CALENDAR_CURRENT_MONTH = "CALENDAR_CURRENT_MONTH";
export const CALENDAR_CHOOSEN_DATE = "CALENDAR_CHOOSEN_DATE";
export const CALENDAR_WRONG_MONTH = "CALENDAR_WRONG_MONTH";